version: '3.8'
services:
  database:
    image: postgres:17
    environment:
      POSTGRES_DB: nest
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: 123
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgresuser -d nest']
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    command: ['npm', 'run', 'start:migrate:prod']
